apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-collector-COLLECTOR_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: metrics
        kind: service
        application: collector-COLLECTOR_NAME
    spec:
      containers:
        # It it connecting to InfluxDB and opens TCP socket for writting to it
        - name: ambassador
          image: metrics-collector-ambassador:v0.1
          readinessProbe:
            tcpSocket:
              port: 8094
            timeoutSeconds: 1
            initialDelaySeconds: 2

        # Should write metrics to localhost:8094
        - name: COLLECTOR_NAME
          image: COLLECTOR_IMAGE

