apiVersion: v1
kind: Service
metadata:
  name: metrics-influxdb
spec:
  selector:
    system: metrics
    kind: storage
    application: influxdb
  ports:
    - port: 8083
      targetPort: 8083
      name: web
    - port: 8086
      targetPort: 8086
      name: api

---
# For now single node for simplicity
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-influx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: metrics
        kind: storage
        application: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:0.13.0
          ports:
            - containerPort: 8083
            - containerPort: 8086
          readinessProbe:
            httpGet:
              path: /ping
              port: 8086
            timeoutSeconds: 1
            initialDelaySeconds: 2

