apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-collector-tap-catalog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: metrics
        kind: service
        application: collector-tap-catalog
    spec:
      containers:
        - name: ambassador
          image: metrics-collector-ambassador:v0.1
          readinessProbe:
            tcpSocket:
              port: 8094
            timeoutSeconds: 1
            initialDelaySeconds: 2
        - name: tap-catalog
          image: metrics-tap-catalog-collector:v0.1
          env:
          - name: CATALOG_PORT
            valueFrom:
              configMapKeyRef:
                name: catalog
                key: catalog-port
          - name: CATALOG_HOST
            valueFrom:
              configMapKeyRef:
                name: catalog
                key: catalog-host
          - name: CATALOG_USER
            valueFrom:
              configMapKeyRef:
                name: catalog
                key: catalog-user
          - name: CATALOG_PASS
            valueFrom:
              configMapKeyRef:
                name: catalog
                key: catalog-pass

