language: go
sudo: required
dist: trusty

go:
  - 1.5

before_install:
  - sudo apt-get update
  - sudo apt-get install -y librados-dev librbd-dev

install:
  - go get github.com/ceph/go-ceph
  - go get github.com/prometheus/client_golang/prometheus
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=collectors.coverprofile ./collectors
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
