@startuml

title Metrics system in TAP

actor User as user
actor Operator as operator


package TAP {

    Node CDH {
    }

    Node CEPH {
    }

    Node K8S {

        frame "K8S API server" as k8sapi {
        }

        frame "Console" as console {
        }

        frame UAA {
        }

        [Grafana] as grafana
        [Prometheus] as prometheus


        cloud "\nK8S Nodes\n" as knodes{
            skinparam cloudBackgroundColor white
        }

        cloud "\nK8S services/pods\n" as kservices {
            folder "Metrics exporters" as ME {

                [Ceph exporter] as CephE
                [CDH exporter] as CDHE
            }

            folder "TAP apps" {
                [Catalog] as tapcatalog
                [Data Catalog] as tapdcatalog
                [others]
            }
        }
    }

    CDH     <-u-     CDHE
    CEPH    <-u-     CephE

}

console     ==>     grafana     :   as iFrame

UAA         <--     grafana     :   REST
grafana     -->     prometheus  :   REST

prometheus  -->     k8sapi
prometheus  -->     knodes
prometheus  -->     kservices

user        -->     console     :   Web
user        -->     grafana     :   Web
operator    -->     console     :   Web
operator    -->     grafana     :   Web with extended privileges


@enduml
